#!/usr/bin/env python3
"""Regenerate the AUTO block in .loop/progress.md from the latest graded run.

Runs after evaluate.py passes (wired into train.yml, before the commit step), so
progress.md always reflects the model that was actually shipped. Only the content
between the AUTO:BEGIN / AUTO:END markers is rewritten; human prose is untouched.

    python .loop/update_progress.py

Stdlib only. Reuses the gate + metrics loaders from evaluate.py so there is one
source of truth for thresholds.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

LOOP = Path(__file__).resolve().parent
ROOT = LOOP.parent
PROGRESS = LOOP / "progress.md"
RUN_HISTORY = ROOT / "RUN_HISTORY.md"

sys.path.insert(0, str(LOOP))
import evaluate  # noqa: E402  (local module, same dir)

BEGIN = "<!-- AUTO:BEGIN (generated by .loop/update_progress.py — do not edit by hand) -->"
END = "<!-- AUTO:END -->"


def latest_run_date() -> str:
    """First data row of RUN_HISTORY.md is the newest run; cell 1 is the date."""
    if not RUN_HISTORY.exists():
        return "unknown"
    for line in RUN_HISTORY.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("| 2") or re.match(r"^\|\s*\d{4}-\d{2}-\d{2}", s):
            cells = [c.strip() for c in s.strip("|").split("|")]
            if cells:
                return cells[0]
    return "unknown"


def verdict(gate: dict, m: dict) -> str:
    r2 = m.get("test_r2")
    mae = m.get("test_mae_lpa")
    n = m.get("n_samples")
    ok = (
        r2 is not None and mae is not None and n is not None
        and r2 >= gate["min_r2_overall"]
        and mae <= gate["max_mae_lpa"]
        and n >= gate["min_samples"]
        and r2 <= gate["leakage_ceiling_r2"]
    )
    return "PASS (SHIP)" if ok else "FAIL (REJECT)"


def build_block() -> str:
    gate = evaluate.load_gate()
    m = evaluate.load_metrics()
    lines = [
        BEGIN,
        "## Latest graded run (auto)",
        "",
        f"- **Date:** {latest_run_date()}",
        f"- **Model:** {m.get('best_model', '?')}, "
        f"{m.get('n_features', '?')} features, "
        f"{m.get('n_samples', '?'):,} training samples"
        if isinstance(m.get("n_samples"), int)
        else f"- **Model:** {m.get('best_model', '?')}, {m.get('n_features', '?')} features",
        f"- **Test R2 (LPA):** {m.get('test_r2')}  |  **MAE:** {m.get('test_mae_lpa')} LPA",
        f"- **Contract:** {verdict(gate, m)}",
        "- **Committed on disk:** yes (models/model_metrics.json reflects this run)",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    text = PROGRESS.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit("progress.md is missing the AUTO:BEGIN/AUTO:END markers.")
    new = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        build_block(),
        text,
        flags=re.DOTALL,
    )
    PROGRESS.write_text(new, encoding="utf-8")
    print("Updated .loop/progress.md auto block.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
